
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcheiukrxyuifvwsmpqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjaGVpdWtyeHl1aWZ2d3NtcHFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MzUwNjAsImV4cCI6MjA2MzUxMTA2MH0.3psPmnHDEoq5VsZZut3Ykd4vu1rFbF_slI2C7OX8wG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
